package com.token.mangowallet.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.token.mangowallet.db.MangoWallet;

import com.token.mangowallet.db.greendao.MangoWalletDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig mangoWalletDaoConfig;

    private final MangoWalletDao mangoWalletDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mangoWalletDaoConfig = daoConfigMap.get(MangoWalletDao.class).clone();
        mangoWalletDaoConfig.initIdentityScope(type);

        mangoWalletDao = new MangoWalletDao(mangoWalletDaoConfig, this);

        registerDao(MangoWallet.class, mangoWalletDao);
    }
    
    public void clear() {
        mangoWalletDaoConfig.clearIdentityScope();
    }

    public MangoWalletDao getMangoWalletDao() {
        return mangoWalletDao;
    }

}
